name: CI/CD mktplc-catalog

on:
  push:
  pull_request:
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  test-job:
    runs-on: ubuntu-latest
    name: test-job
    steps:
      - name: Sets MODIFIED_BRANCH_NAME
        env:
          name: "${{env.BRANCH_NAME}}"
        run: |
          echo "MODIFIED_BRANCH_NAME=${name/\//-}" >> $GITHUB_ENV
      - name: read env variable
        run: |
          echo ${{ env.BRANCH_NAME }}
          echo ${{ env.MODIFIED_BRANCH_NAME }}

