name: CI/CD mktplc-catalog

on:
  push:
  pull_request:
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  env-job:
    runs-on: ubuntu-latest
    outputs:
      modified-branch-name: ${{ steps.env.outputs.MODIFIED_BRANCH_NAME }}
    name: test-job
    steps:
      - name: Sets MODIFIED_BRANCH_NAME
        id: env
        env:
          name: "${{env.BRANCH_NAME}}"
        run: |
          echo "MODIFIED_BRANCH_NAME=${name/\//-}" >> ${GITHUB_OUTPUT}

  test-job-1:
    runs-on: ubuntu-latest
    needs:
      - env-job
    steps:
      - name: show envs
        run: |
          echo ${{ needs.env-job.outputs.modified-branch-name }} 

  test-job-2:
    runs-on: ubuntu-latest
    needs:
      - env-job
    steps:
      -  name: show envs
         run: |
           echo ${{ needs.env-job.outputs.modified-branch-name }} 

