name: Linter
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:
jobs:
  linter:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint with Pylint
        run: |
          flake8 $(git diff origin/main --name-only --diff-filter=d)
