name: "Update Pull Request"
on: 
  pull_request:
    types:
      - opened

permissions:
  contents: read
  pull-requests: write

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: the-wright-jamie/Update-PR-Info-Action@master
        continue-on-error: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: '[a-z\d-_.\\/]+'
          head-branch-regex: 'ci-update-dppgo'
          body-template: |
           See [this](https://github.com/mbiagetti/github-action-poc/blob/main/README.md) README
          
            - [ ] first task
            - [ ] second task
            - [ ] third task
          body-update-action: "suffix"