name: Test dynamic secrets reading by env var


on:
  push:

env:
  ENV: 'dev'


jobs:

  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: test
        env:
          THE_SECRET_NAME: ${{  format('API_{0}_PWD', env.ENV) }}
        run: |
          printenv
          echo "${THE_SECRET_NAME}" >> secret_name.txt
      - name: ANOTHER test
        env:
          THE_SECRET_VALUE: ${{ secrets[format('API_{0}_PWD', env.ENV) ] }}
        run: |
          echo "${THE_SECRET_VALUE}" >> secret_value.txt

      # Upload the contents of Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            secret_name.txt
            secret_value.txt
          retention-days: 1
